### ISSUE TITLE
Should we skip None and empty lists as children?

### ISSUE THREAD

**Issue by pauleveritt** [jviide/htm.py#14]
Imagine the following code:

```python
message1 = None
print('<div>{message1}</div>')
# Result: H(tag='div', props={}, children=[None])
message2 = []
print('<div>{message2}</div>')
# Result: H(tag='div', props={}, children=[[]])
```

I don't think this really causes too much of a problem, as a `render()` can sort it out. Just curious, though, how `htm` handles undefined, null, empty sequences, etc.

**Comment by jviide** [comment]
In my mind that's outside of htm.py's scope. How `None` and `[]` should be interpreted really depends on the the renderer. For example, if htm.py's output would be used as an input to Preact then `None`/`null` children are considered to be sort of placeholders for items that may appear there later.

**Comment by pauleveritt** [comment]
Very good, exactly what I needed, thanks.
