### ISSUE TITLE
Introduce some type hints for the VDOM

### ISSUE THREAD

**Issue by pauleveritt** [jviide/htm.py#15]
Can we do some type hints for the VDOM? For example:

```python
Children = Union[str, List]
VDOM = NamedTuple("VDOM", [
    ('tag', str),
    ('props', Mapping),
    ('children', Children),
])
```

We alas can't model the recursion due to known issues in `mypy`. But the above is helpful all the same.

If agreed, I will:

- Do a branch that has the above
- Make sure it is available at `htm.VDOM`
- Change the inner function to say it returns it
- Add some documentation
- Change the tests to use it

Downside: makes Python 3.6 the minimum version, if we do it as annotations.

**Comment by pauleveritt** [comment]
I got some help and have a version that seems to do the right thing, including with recursion.

@jviide Before I do a PR, I want to check to see if you are ok with this. It would also mean doing the dance to flag that this package has type hints.

**Comment by jviide** [comment]
Sure, go ahead. I'm interested in seeing how the type hints work 🙂

Couple of things to remember in the typings: `tag` is not necessarily always a `str`, as it can be pretty much anything depending on the `h` function. For example in some contexts tag could be a function. `children` can also contain (again, depending on the `h` function) iterators, numbers and so on.

In other words, is it possible to base the type hints on the `h` function?

**Comment by pauleveritt** [comment]
You're right. I should experiment with doing it in my constraints (e.g. in `viewdom`) and see if it adds value there. If not, it won't add value in the much broader types you describe. I will also see if I can have it based on the typing from the `h`.

Closing in this repo.
