### ISSUE TITLE
Add Custom Encoding To Enable Template Syntax

### ISSUE THREAD

**Issue by rmorshea** [jviide/htm.py#2]
I've been working to enable `htm`-like syntax in Python for the past few weeks before I found your project, but I'd like to contribute a feature from my own project [`htm-pyx`](https://github.com/rmorshea/htm-pyx) to yours instead of to developing mine.

> For context I'm using `htm-pyx` in another project of mine called [`IDOM`](https://github.com/rmorshea/idom)

That feature being a custom "html" file encoding that allows you two write HTM using f-string-like syntax:

```python
# coding=html
my_div = html"<div/>"
```

This was originally inspired by https://github.com/dropbox/pyxl, but I think I've improved on it in a number of was:

1. Ability to register/deregister the encoding to the current Python interpreter via a CLI.
2. Automatic integration with IPython and Jupyter Notebooks.

**Comment by notpushkin** [comment]
@rmorshea Just an idea but perhaps you could instead make a generic string tagging processor, something like [tagged templates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_templates) in JS? Then it would be easily combined with this library and perhaps some others too.

**Comment by pauleveritt** [comment]
@notpushkin That's what [tagged](https://github.com/jviide/tagged) from @jviide does, right?

**Comment by notpushkin** [comment]
@pauleveritt Almost! Using a custom encoding, we can omit the parenthesis as well. Basically

```py
# coding=tagged
from tagged import tag

@tag
def mytag(strings, values):
    return strings, values

strings, values = mytag"1 + {2} equals {1 + 2}"
# strings == ('1 + ', ' equals ', '') and values == (2, 3)
```

is what I'm talking about.

**Comment by pauleveritt** [comment]
Ah, got it. And it isn't a fork of Python to get the new parser. Clever. 😄 

Curious what this means for tracebacks, debuggers, etc. Does the intermediate step preserve the ability to get to the actual line with the problem?

**Comment by jviide** [comment]
A custom encoding making `html"<div />"` and `mytag"<div />"` possible would be really cool! On the other hand editors, linters etc. would probably tend to flag `html"<div />"` as a syntax error. For me personally that's a pretty big price to pay for being able to drop the parentheses, as I'm totally dependent on VSCode's live linting and autoformatting 🙂

That said, I think this is an interesting concept and I'm open to it. One option would be to add this kind of functionality to [`tagged`](https://github.com/jviide/tagged). Or maybe even create a new package that implements an encoding for rewriting `mytag"foo{1}bar"` calls to `mytag("foo{1}bar")`, along with the CLI goodies from `htm-pyx`? That way `tagged` and `htm.py` would interop with the encoding package, but the Python ecosystem could also use (and build upon) it without necessarily depending on `tagged` and `htm.py`.

**Comment by jviide** [comment]
Here's a quick and messy gist demonstrating what I mean: https://gist.github.com/jviide/8805c46a404fd613b395ca8525fd3f43

**Comment by rmorshea** [comment]
@jviide, you're right. As I've been experimenting with `htm-pyx` I've discovered that the combination of invalid syntax and the custom encoding makes it pretty much impossible to interoperate with linting tools in the Python ecosystem. Given that I also depend on `black` to auto-format my code this is kind of a show stopper.

That said, I think there are still paths forward.

**Instead of a custom encoding** we could use [`sys.meta_path`](https://docs.python.org/3/library/sys.html#sys.meta_path) to add a custom importer that would transpile modules just before they were imported.

**To fix invalid syntax** we could transpile these valid syntaxes:
 
1. `~f"<div/>"` - because `~` is not implemented for `str` we can identify this in a file and transpile it based on some comment or import at the top of the file (e.g. `# dialect=html`).

2. `html % "<div/>"` - not really sure how we'd figure out when to transpile this, but this syntax would allow the code to function even if you didn't transpile since `html` could fall back to doing exactly what `htm` does now via `__mod__`.

3. `"<div/>" // html` similar to **1** `//` is not implemented for `str` and thus can easily be identified as something that needs to be transpiled. Similarly to **2** though `html` can implement `__rfloordiv__` which is triggered if he LHS of an expression does not implement `//`. We could use an of the `str`'s non-implemented operators (e.g. `@`, `&`, `*`).

Personally, I'm partial to **2** or **3**.

**Comment by rmorshea** [comment]
I also found that [Guido is against](https://mail.python.org/archives/list/python-ideas@python.org/message/4CUUZL5YSQD6JTYATSPNJ2M3WDBHWO4R/) the `html"<div/>"` template syntax so that's another reason to avoid it.

**Comment by rmorshea** [comment]
I'm going to close this issue, but when I implement some of the ideas above I'll comment here to get some feedback.

**Comment by jviide** [comment]
Ok, sounds good! Looking forward to it 🙂

By the way, using the `html("""...""")` form hasn't been too bad in practice either. I'm just spitballing here, but maybe enhanced editor & tooling support (linter/formatter plugins or something similar to [the lit-html plugin for VSCode](https://marketplace.visualstudio.com/items?itemName=bierner.lit-html)) would make the coding experience more enjoyable. Something to explore in the future perhaps 🚀

**Comment by rmorshea** [comment]
Initial progress: https://github.com/rmorshea/pyalect

**Comment by pauleveritt** [comment]
@jviide Your point about tooling support is (not surprisingly) very important for me.

For tagged and htm.py it would seem a plugin would need to accomplish:

- Know that html"" == f"" (meaning, the string is an f-string)
- Inside that string, enable HTML language injection rules
- But look for Python expressions in curly braces

Anything else?

**Comment by rmorshea** [comment]
@pauleveritt that sounds about right. And that's actually pretty much what I've done in [htm-pyx](https://github.com/rmorshea/htm-pyx) (a lot of which was copied from my [`fstr`](https://github.com/rmorshea/fstr) repo). That said, I've started to have some doubts about the `html"..."` syntax for reasons listed above by @jviide.

I'm feeling pretty happy about [Pyalect](https://github.com/rmorshea/pyalect) though, so feedback there would be great. In short, you can use Pyalect to create a custom transpiler that will be engaged at runtime based on a `# dialect=...` header comment in your `.py` files. You can register transpilers to the current Python interpreter via the CLI, or programatically to the current Python session in your application's entry point as shown below:

> `entry_point.py`

```python
import ast
import pyalect

class MyTranspiler:
    def __init__(self, dialect: str) -> None: ...
    def transform_src(self, source: str) -> str: ...
    def transform_ast(self, node: ast.AST) -> ast.AST: ...

pyalect.register("my_dialect", MyTranspiler)

import my_module
```

> `my_module.py`

```python
# dialect=my_dialect
...
```

**Comment by rmorshea** [comment]
Just merged this work into IDOM:

https://idom.readthedocs.io/en/latest/extras.html#python-language-extension

The transpiler implementation uses `htm.htm_parse`, which could probably use some interface improvements to make the code on my end just a little bit cleaner.

https://github.com/rmorshea/idom/blob/master/src/py/idom/dialect.py

**Comment by jviide** [comment]
Yeah, for use cases like this, htm.py could maybe offer a visitor interface (or something) for consuming the htm_parse's return values. It would be best if you wouldn't have to depend on the specific opcodes returned by htm_parse, as I originally envisioned them to be an internal implementation detail 🙂
