### ISSUE TITLE
Deploy new docs

### ISSUE THREAD

**Issue by pauleveritt** [jviide/htm.py#8]
Thanks for merging the branch with the docs. We should discuss how to make the docs visible.

Do you want them on RTD? If so, we should probably move away from my login and my fork. I can help you get it running via commits and Travis, but it's going to be some work for you.

We could also look at GitHub Pages deployment. We could also look at GitHub Actions.

Once deployed, we need to put it in various places, e.g. the repo description, badges on the README, text of the README, etc.

**Comment by pauleveritt** [comment]
@jviide If the docs are useful, can we look at deploying them?

**Comment by jviide** [comment]
Hi - sorry for the late reply.

The tests are now auto-deploying to GitHub pages via GitHub Actions. I also took the opportunity to switch the tests from CircleCI to GitHub Actions.

The published GitHub Pages are at https://jviide.github.io/htm.py/

**Comment by pauleveritt** [comment]
@jviide Can we mention this in the README and the GitHub description, then close this?

**Comment by jviide** [comment]
Absolutely! I added the README mention and GitHub description link, and published v0.1.1 of the package to https://pypi.org/project/htm/0.1.1/

Thanks for looking after this issue 🙂
